name: Deploy Node app on AWS Elastic Beanstalk
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r build-web-${{ github.run_id }}.zip . -x '*.git* node_modules/\*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: test-app
        environment_name: test-app-staging
        version_label: build-web-${{ github.run_id }}
        region: ap-southeast-1
        deployment_package: build-web-${{ github.run_id }}.zip
        
